services:
  ondine-db:
    image: yobasystems/alpine-mariadb:latest
    container_name: ondine-db
    hostname: ondine-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=DBManagerOndine2025
      - MYSQL_DATABASE=ondine
      - MYSQL_USER=ondine
      - MYSQL_PASSWORD=DBManagerOndine2025
    volumes:
      - ondine_data:/var/lib/mysql
    ports:
      - "13306:3306"

  ondine:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: ondine
    hostname: ondine
    restart: unless-stopped
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
      # Database configuration
      - DB_DRIVER=mariadb
      - MYSQL_HOST=ondine-db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=ondine
      - MYSQL_USER=ondine
      - MYSQL_PASSWORD=DBManagerOndine2025
      # JWT Configuration
      - JWT_SECRET=your_secure_jwt_secret_change_in_production
      # Initial seeds
      - SEED_PROFILE_NAME=Administrator
      - SEED_PROFILE_PERMISSIONS={"profiles":1,"users":1}
      - SEED_ADMIN_USERNAME=sysadmin
      - SEED_ADMIN_PASSWORD=SecureAdmin2025
    volumes:
      - ondine_files:/var/www/html/public
    depends_on:
      - ondine-db

  ondine-nginx:
    image: nginx:mainline-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ondine_files:/var/www/html/public:ro
    container_name: ondine-nginx
    hostname: ondine-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - ondine

volumes:
  ondine_data:
  ondine_files:

networks:
  default:
    name: container-network
    external: true