name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
    - name: Install dependencies
      run: composer install --no-progress --no-suggest
    - name: Run static analysis and tests
      run: composer validate || true
    - name: Run phpstan
      run: composer phpstan
    - name: Run phpcs (fail only on errors)
      run: |
        set -euo pipefail
        ./vendor/bin/phpcs --standard=phpcs.xml.dist src --report=json > phpcs-report.json || true
        php -r "\$r=json_decode(file_get_contents('php://stdin'), true); exit((int)(\$r['totals']['errors']>0));" < phpcs-report.json
    - name: Run tests
      run: composer test
